#!/bin/bash

jdtls_build_path=/usr/local/share/eclipse.jdt.ls/org.eclipse.jdt.ls.product/target/repository

jar="$(find $jdtls_build_path/plugins -name "org.eclipse.equinox.launcher_1*")"
config=$jdtls_build_path/config_mac
workspace=$HOME/.local/share/jdtls

mkdir -p "$workspace"

/usr/local/opt/openjdk@11/bin/java \
	-Declipse.application=org.eclipse.jdt.ls.core.id1 \
	-Dosgi.bundles.defaultStartLevel=4 \
	-Declipse.product=org.eclipse.jdt.ls.core.product \
	-Dlog.protocol=true \
	-Dlog.level=ALL \
	-Xms1g \
	-Xmx2G \
	-jar "$jar" \
	-configuration "$config" \
	-data "$workspace" \
	--add-modules=ALL-SYSTEM \
	--add-opens java.base/java.util=ALL-UNNAMED \
	--add-opens java.base/java.lang=ALL-UNNAMED
