#!/bin/bash
set -e

WATCH_COMMAND=""

MAX_WORKERS=$(kubectl get hpa concourse-worker-hpa -o json | jq '.spec.maxReplicas')

for i in $( seq 0 $MAX_WORKERS ); do
   WATCH_COMMAND="${WATCH_COMMAND} kubectl exec concourse-worker-${i} df | grep concourse-work-dir | sed 's/^/conourse-worker-${i} ---> /';"
done

WATCH_COMMAND="${WATCH_COMMAND} kubectl get hpa"
echo $WATCH_COMMAND
watch -n 1 $WATCH_COMMAND
