#!/bin/bash
set -euo pipefail

source "$(dirname "$0")/../util.sh"

os=$(uname -s)
# this script installs or updates lsp servers and their dependencies

pprint () {
   print_green "\n→ $1"
}

npm_install () {
   pprint $1
   npm install -g $1
}

pprint efm-langserver
if [ "$os" = "Darwin" ]; then
   brew install efm-langserver
else
   sudo pacman -S efm-langserver
fi

npm_install prettier

npm_install prettier-plugin-java

npm_install standard

npm_install typescript
npm_install typescript-language-server

npm_install vscode-json-languageserver

npm_install yaml-language-server

npm_install elm
npm_install elm-test
npm_install elm-format
npm_install @elm-tooling/elm-language-server

npm_install vscode-css-languageserver-bin

npm_install bash-language-server
